services:
  - type: cron
    name: rentas-hammocks
    env: python
    schedule: "0 13 * * *" 
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: python fb_rent_scraper.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9  # <--- Esta es la línea mágica que soluciona el error
      - key: TOKEN
        value: os.getenv("TOKEN")
      - key: CHAT_ID
        value: os.getenv("CHAT_ID")
    autoDeploy: false
