services:
  - type: cron
    name: rentas-hammocks
    env: python
    schedule: "0 13 * * *"  # 5 campos: minuto(0) hora(13) día(*) mes(*) día_semana(*)
    buildCommand: pip install -r requirements.txt && playwright install chromium --with-deps
    startCommand: python fb_rent_scraper.py
    envVars:
      - key: TOKEN
        value: 8828207901:AAGLALCvQ0lagsrl7m6qcDfiIWXruiL2Xsw
      - key: CHAT_ID
        value: 6456127410
    autoDeploy: false
